### ISSUE TITLE
Not able to compile and run on a fresh install.

### ISSUE THREAD

**Issue by wakasturner** [S1ink/UE5-LidarSim#1]
I tried to compile UE5-LidarSim using UE 5.3.2 on windows but it fails to compile.

When trying to run it gives me following, 
> The following modules are missing or built with a different engine version:
>   UESim
>   GPUPointCloudRenderer
>   GPUPointCloudRendererEditor
>   LidarSim
> Would you like to rebuild them now?

And if try to proceed with re compiling i get the following error.
> UESim could not be compiled. Try rebuilding from source manually.

What might i be doing wrong?

Windows 10
Unreal Engine 5.3.2 (Installed using Epic game Launcher)
Nvidia RTX 3090

**Comment by S1ink** [comment]
This is my bad for the lack of documentation (still very much a work in progress). You will need to check out the releases where I have zipped the third party libs required for the project (github would not accept the large files). The post there tells which directory they should be extracted under, but let me know if you have further questions about what the directory structure should end up looking like. After that it may still be possible that on startup it won't build automatically in which case you should open the Visual Studio project and build manually - that has worked for me in the past. Also, if you only need the point cloud renderer, it should be as simple as copying the folder with that plugin to a new project as it has no dependencies.
Hope this helps!

**Comment by wakasturner** [comment]
Thanks for clearing that up! I've checked out the files on the release page.

Before diving into my own project, I want to make sure I understand how the point clouds are viewed in the viewport. So, I'm planning to explore your project as it is to confirm compatibility. I'll give the plugins zip you provided a go on Monday.

Might have a few more questions for you, hope that's cool! Thanks a bunch!

**Comment by S1ink** [comment]
Yeah no problem! I'm glad someone else can get something out of my work. I did also get around to including a note in the readme so this hopefully will not happen in the future.
